remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 


title: Gocli
description: Gocli, a Python-based command line interface developed using Typer-cli, aims to aid QA testers by offering indispensable features during the testing process.

